### ISSUE TITLE
Adding words to lists via context menu

### ISSUE THREAD

**Issue by sabretou** [sdar/Multiple-Highlighter#1]
Hello, this add-on looks like a great substitute for the unmaintained Vocabulary Highlighter. I hope this is the right place to provide suggestions, but would you please consider adding a context menu option to add words to the lists.

I am using this addon for educational purposes, and I have to add many words to the lists as I learn them. It would be very convenient for me if I can add them on the go, rather than having to add them manually to the list. I am also worried that the list might get deleted or modified by accident, so I would rather not have to touch it manually at all.

Thank you for reading. Have a good day.

**Comment by sdar** [comment]
Sorry for the delay, and thank you for your suggestion, I have some plans to improve the whole addon, new interface better/faster code and new options, one of the options was a "highlight selected text" option, but I'll look into adding a context menu for adding words to the lists too.

A sneak preview of the new interface:
![mh](https://cloud.githubusercontent.com/assets/11141643/14490071/eb7b5bd4-0170-11e6-80fe-e2a49c12dc52.png)

**Comment by sdar** [comment]
So I've taken a look into this, it seems that the after-mentioned "Vocabulary Highlighter" opens a new window where you can select word, pen, note and if it's going to be highlighted, i was thinking that maybe it could be faster using a different approach (see image below):
![cm](https://cloud.githubusercontent.com/assets/11141643/14520640/e5ddebfa-0225-11e6-81a6-9769bffd2e5f.png)

Any thoughts?

Also do you need notes?, maybe i can add them without decreasing performance too much

**Comment by sabretooth1** [comment]
I don't need notes myself, so that's a no for me. And that screenshot looks exactly like how I envisioned it would word for this addon! It's looking great. :)

**Comment by sdar** [comment]
Feature added as well as a new interface and more features.
https://github.com/sdar/Multiple-Highlighter/commit/5349018b0be7a2680a57a95b6582bbbb1bc9ae47

I'll send the addon to amo (firefox addon webpage) now.
