### ISSUE TITLE
Incompatible with Rikaichan

### ISSUE THREAD

**Issue by sabretou** [sdar/Multiple-Highlighter#6]
I was using the add-on to study Japanese with, many months ago. Specifically, I'd mark the kanji I'd learned to highlight, which helped a lot. I had to abandon study for a few months, and was looking to get back into it with the new version of the add-on.

Problem is, the add-on Rikaichan works only partially. If certain kanji are highlighted, Rikaichan does not read them as contiguous to the non-highlighted kanji.

For eg. if you have the word 世界, Rikaichan shows the definition for that word, which it auto-detects. However, if the kanji 世 is highlighted, then Rikaichan only shows the definition for that single kanji alone, because it is unable to detect the whole word as 世界.

I understand if this is not something you want to fix, because it is a very niche problem. For help in determining what the problem is, however, I'd like to state that the very similar add-ons Vocabulary Highlighter and Phrase Highlighter do not have this problem (although they do have other problems, which is why I was using this add-on).

**Comment by sdar** [comment]
I'll take a look if it can be fixed as a temp workaround expect a fix around next week if not I'll try to fix it while fixing the overlapping issues the addon currently have.

**Comment by sdar** [comment]
Ok I've installed the Rikaichan addon and diagnosed the problem will try to send the addon to addons.mozilla tonight for revision so the update should be available in 1-3 days, I'll add an unsigned version here tomorrow morning if you can't wait but you'll have to disable signing or use the unbranded firefox builds.

**Comment by sabretooth1** [comment]
Hey, that's excellent. Thanks, I'll wait for the update on addons.mozilla, no hurry.

**Comment by sdar** [comment]
Firefox will auto-update the addon you don't need to check it yourself.

**Comment by sdar** [comment]
fixed with commit 0ad3b52

**Comment by sdar** [comment]
I'm not gonna add the unsigned version cause the signed one is already on AMO (addons.mozilla.org) and should update automatically for all users.
